let dishesToDo = ['big platter'];
dishesToDo.unshift('large plate');
console.log(dishesToDo);
dishesToDo.unshift('small plate');
console.log(dishesToDo);
dishesToDo.unshift('cereal bowl');
console.log(dishesToDo);
dishesToDo.unshift('mug');
console.log(dishesToDo);
dishesToDo.unshift('dirty spoon');
console.log(dishesToDo);

dishesToDo.shift();
console.log(dishesToDo);
dishesToDo.shift();
console.log(dishesToDo);
dishesToDo.shift();
console.log(dishesToDo);
dishesToDo.shift();
console.log(dishesToDo);
dishesToDo.shift();
console.log(dishesToDo);
dishesToDo.shift();
console.log(dishesToDo);
